os:
  - linux
  - osx

language: node_js
node_js:
  - "iojs-v2.2.1"

env:
  global:
    - target: 0.28.2 # electron version
    - bin_dir: ./node_modules/electron-updater-tools/bin

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8 gcc-4.8-multilib g++-4.8-multilib libelf-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - npm install node-gyp -g
  - npm install electron-prebuilt@${target} -g
  - npm install

script:
  - $bin_dir/elb configure x64 release --target ${target}
  - $bin_dir/elb configure x86 release --target ${target}